### ISSUE TITLE
Document behaviour of TimerHeap::insert when key exists

### ISSUE THREAD

**Issue by jonhoo** [andrewjstone/timer_heap#3]
Currently, `TimerHeap::insert` returns a `Result`, with no explanation in the docs for why this is the case. From reading the code I gather that you'd see an error if a timer already exists for the given key already exists; this should be documented.

Separately, I'm not sure if this is the desired behaviour for a key collision. `HashMap` and `BTreeMap` handle this by returning an `Option<T>`, which will return the *replaced* entry on a collision. It's not entirely clear what the right thing is to do for replacement for `TImerHeap` though. I'm partial to keeping whichever has the shorter timeout, but that may require some discussion.

**Comment by jonhoo** [comment]
Actually, ideally, the replacement policy should probably be customizeable. Or you could provide two different methods (`replace` and `insert`) to distinguish the two use-cases. In my particular case, I want to replace, which means that I currently have to call `remove` and then `insert`.

**Comment by andrewjstone** [comment]
I think I like the `replace` and `insert` solution. The reason I didn't return an option is because unlike HashMap and BTreeMap, removal affects the underlying heap as well. So if the user did want to keep the existing value he'd have to reinsert it, but the other value was needlessly inserted into the heap. This has the downside though that you always have to cancel a timer before you can re-add one with the same key which has overhead as well, and as you point out is probably the most common case.

I like the simplicity of the the separate methods and will add them and document appropriately. Thanks for the feedback.

**Comment by andrewjstone** [comment]
Fixed by https://github.com/andrewjstone/timer_heap/commit/f3e973070d2863ad433935aea45e866b86862bc8
